name: Quality
on: pull_request

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Formatting and Linting
        run: bun biome ci .

      - name: Run Type Checking
        run: bun run tsc
      
      - name: Verify build
        run: bun run build

      - name: Run Tests
        run: bun run test
      
